package gov.usgs.cida.pubs.webservice.security;

public enum PubsRoles {
	PUBS_ADMIN,
	PUBS_TAGGING_USER,
	PUBS_SPN_USER,
	PUBS_CATALOGER_USER,
	PUBS_SPN_SUPERVISOR,
	PUBS_CATALOGER_SUPERVISOR,
	AD_AUTHENTICATED,
	PUBS_AUTHORIZED
}
